// Auto-generated by: npm run db:gen-types
// Run after `supabase db reset` to regenerate from your local schema.
// This is a placeholder — the real file is generated by Supabase CLI.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  __InternalSupabase: {
    PostgrestVersion: "12"
  }
  public: {
    Tables: {
      workspaces: {
        Row: {
          id: string
          name: string
          slug: string
          owner_id: string | null
          settings: Json
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          owner_id?: string | null
          settings?: Json
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          owner_id?: string | null
          settings?: Json
          created_at?: string
        }
        Relationships: []
      }
      workspace_members: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_members_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          }
        ]
      }
      agents: {
        Row: {
          id: string
          workspace_id: string
          name: string
          description: string | null
          system_prompt: string
          model: string
          tools: Json
          schedule: string | null
          input_schema: Json | null
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name: string
          description?: string | null
          system_prompt: string
          model?: string
          tools?: Json
          schedule?: string | null
          input_schema?: Json | null
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          name?: string
          description?: string | null
          system_prompt?: string
          model?: string
          tools?: Json
          schedule?: string | null
          input_schema?: Json | null
          status?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "agents_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          }
        ]
      }
      workflows: {
        Row: {
          id: string
          workspace_id: string
          name: string
          description: string | null
          steps: Json
          trigger: Json | null
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name: string
          description?: string | null
          steps?: Json
          trigger?: Json | null
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          name?: string
          description?: string | null
          steps?: Json
          trigger?: Json | null
          status?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workflows_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          }
        ]
      }
      runs: {
        Row: {
          id: string
          agent_id: string | null
          workflow_id: string | null
          workspace_id: string
          input: Json | null
          output: Json | null
          status: string
          error: string | null
          duration_ms: number | null
          token_count: number | null
          cost_usd: number | null
          triggered_by: string | null
          created_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          agent_id?: string | null
          workflow_id?: string | null
          workspace_id: string
          input?: Json | null
          output?: Json | null
          status?: string
          error?: string | null
          duration_ms?: number | null
          token_count?: number | null
          cost_usd?: number | null
          triggered_by?: string | null
          created_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          agent_id?: string | null
          workflow_id?: string | null
          workspace_id?: string
          input?: Json | null
          output?: Json | null
          status?: string
          error?: string | null
          duration_ms?: number | null
          token_count?: number | null
          cost_usd?: number | null
          triggered_by?: string | null
          created_at?: string
          completed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "runs_agent_id_fkey"
            columns: ["agent_id"]
            isOneToOne: false
            referencedRelation: "agents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "runs_workflow_id_fkey"
            columns: ["workflow_id"]
            isOneToOne: false
            referencedRelation: "workflows"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "runs_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          }
        ]
      }
      tools: {
        Row: {
          id: string
          workspace_id: string
          name: string
          type: string
          config: Json
          auth_method: string | null
          rate_limit: Json | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name: string
          type: string
          config?: Json
          auth_method?: string | null
          rate_limit?: Json | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          name?: string
          type?: string
          config?: Json
          auth_method?: string | null
          rate_limit?: Json | null
          status?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tools_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          }
        ]
      }
      secrets: {
        Row: {
          id: string
          workspace_id: string
          key: string
          encrypted_value: string
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          key: string
          encrypted_value: string
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          key?: string
          encrypted_value?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "secrets_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          }
        ]
      }
      notifications: {
        Row: {
          id: string
          workspace_id: string
          agent_id: string | null
          run_id: string | null
          type: string
          title: string
          payload: Json | null
          read: boolean
          actioned: boolean
          action_taken: string | null
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          agent_id?: string | null
          run_id?: string | null
          type: string
          title: string
          payload?: Json | null
          read?: boolean
          actioned?: boolean
          action_taken?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          agent_id?: string | null
          run_id?: string | null
          type?: string
          title?: string
          payload?: Json | null
          read?: boolean
          actioned?: boolean
          action_taken?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_agent_id_fkey"
            columns: ["agent_id"]
            isOneToOne: false
            referencedRelation: "agents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      is_workspace_member: {
        Args: { ws_id: string }
        Returns: boolean
      }
      has_workspace_role: {
        Args: { ws_id: string; required_role: string }
        Returns: boolean
      }
    }
    Enums: Record<string, never>
  }
}
